package com.alexhappytim.edhTGbot.tgBot;

public enum BotState {
    IDLE,
    REGISTER_NAME,
    REGISTER_SURNAME,
    CREATING_TOURNAMENT_NAME,
    CREATING_TOURNAMENT_DATE,
    CREATING_TOURNAMENT_CONFIRM,
    JOINING_TOURNAMENT,
    MANAGING_TOURNAMENT,
    SENDING_RESULT
}
